### ISSUE TITLE
Got error while running npm start

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/blog#1]
```
ERROR Process failed: layout/_scripts/bootstrap/.gitkeep
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/media/sf_Share/blog/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/media/sf_Share/blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/media/sf_Share/blog/node_modules/hexo/lib/theme/index.js:37
:10)
    at Theme.setView (/media/sf_Share/blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /media/sf_Share/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/media/sf_Share/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/media/sf_Share/blog/node_modules/bluebird/js/r
elease/promise.js:502:31)
    at Promise._settlePromise (/media/sf_Share/blog/node_modules/bluebird/js/release/prom
ise.js:559:18)
    at Promise._settlePromise0 (/media/sf_Share/blog/node_modules/bluebird/js/release/pro
mise.js:604:10)
    at Promise._settlePromises (/media/sf_Share/blog/node_modules/bluebird/js/release/pro
mise.js:683:18)
    at Promise._fulfill (/media/sf_Share/blog/node_modules/bluebird/js/release/promise.js
:628:18)
    at Promise._resolveCallback (/media/sf_Share/blog/node_modules/bluebird/js/release/pr
omise.js:423:57)
    at Promise._settlePromiseFromHandler (/media/sf_Share/blog/node_modules/bluebird/js/r
elease/promise.js:514:17)
    at Promise._settlePromise (/media/sf_Share/blog/node_modules/bluebird/js/release/prom
ise.js:559:18)
    at Promise._settlePromise0 (/media/sf_Share/blog/node_modules/bluebird/js/release/pro
mise.js:604:10)
    at Promise._settlePromises (/media/sf_Share/blog/node_modules/bluebird/js/release/pro
mise.js:683:18)
    at Promise._fulfill (/media/sf_Share/blog/node_modules/bluebird/js/release/promise.js
:628:18)
    at /media/sf_Share/blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /media/sf_Share/blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

**Comment by xcatliu** [comment]
Fixed
